server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: D:\spring-java\config-central\ms-config-repository
